### ISSUE TITLE
Can't export to CSV. AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

### ISSUE THREAD

**Issue by ryandahlke** [percolate/ec2-security-groups-dumper#21]
Using Python 3.6. Same error with 2.7. Virtualenv.  On macOS 10. 
I could export to JSON but not CSV. 

I tried changing output = StringIO.StringIO() to output = StringIO() like I saw in another thread. It didn't work. 

(env) host:ec2-security-groups-dumper user$ ec2-security-groups-dumper --csv > sg.csv
Traceback (most recent call last):
  File "/Users/user/Documents/aws/ec2-security-groups-dumper/env/bin/ec2-security-groups-dumper", line 11, in <module>
    sys.exit(main())
  File "/Users/user/Documents/aws/ec2-security-groups-dumper/env/lib/python3.6/site-packages/ec2_security_groups_dumper/main.py", line 376, in main
    print(firewall.csv)
  File "/Users/user/Documents/aws/ec2-security-groups-dumper/env/lib/python3.6/site-packages/ec2_security_groups_dumper/main.py", line 255, in csv
    output = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

**Comment by thekozak** [comment]
For python 3.6, This worked for me:

vim /usr/local/lib/python3.6/site-packages/ec2_security_groups_dumper/main.py
```
try:
    from StringIO import StringIO
except ImportError:
    # original line
    #from io import StringIO

    # fix
    import io as StringIO
```

**Comment by buzen247** [comment]
I simply downgraded to previous version (1.8.0).. I am stuck on python 2.7

**Comment by erich745** [comment]
In relation to using python 2.7

Line 255 - 

#original line >  output = StringIO.StringIO()
output=StringIO()

Fixed CSV dumps for me..

**Comment by lra** [comment]
Feel free to open PRs! ;)
