### ISSUE TITLE
Error while using CSV flag

### ISSUE THREAD

**Issue by abdulirfan3** [percolate/ec2-security-groups-dumper#3]
@lra 
here is what i get. again the JSON works fine, it is the CSV

[root@ip-10-0-1-32 ~]# ec2-security-groups-dumper --csv
Traceback (most recent call last):
File "/usr/local/bin/ec2-security-groups-dumper", line 9, in 
load_entry_point('ec2-security-groups-dumper==1.1', 'console_scripts', 'ec2-security-groups-dumper')()
File "/usr/local/lib/python2.6/site-packages/ec2_security_groups_dumper/main.py", line 281, in main
print firewall.csv
File "/usr/local/lib/python2.6/site-packages/ec2_security_groups_dumper/main.py", line 213, in csv
writer.writeheader()
AttributeError: DictWriter instance has no attribute 'writeheader'
[root@ip-10-0-1-32 ~]#

**Comment by ianwestcott** [comment]
@abdulirfan3 it looks like you're using Python 2.6; this script uses the `writeheader` attribute of the `DictWriter` class, which requires Python 2.7. If Python 2.7 is available in your environment, you should consider upgrading.

**Comment by lra** [comment]
or feel free to submit a PR to support py26 ;)
