### ISSUE TITLE
issues with csv 

### ISSUE THREAD

**Issue by ghoshtapo** [percolate/ec2-security-groups-dumper#6]
Thanks for coming up with this nice tool. But I get an error for csv option

ec2-security-groups-dumper --csv
Traceback (most recent call last):
  File "/usr/local/bin/ec2-security-groups-dumper", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/ec2_security_groups_dumper/main.py", line 295, in main
    print firewall.csv
  File "/Library/Python/2.7/site-packages/ec2_security_groups_dumper/main.py", line 228, in csv
    for fr in self.rules:
  File "/Library/Python/2.7/site-packages/ec2_security_groups_dumper/main.py", line 162, in rules
    rules_grants_cidr_ip=grant_row['cidr_ip'])
  File "/Library/Python/2.7/site-packages/ec2_security_groups_dumper/main.py", line 57, in **init**
    assert rules_ip_protocol in (u'tcp', u'udp', u'icmp', None)
AssertionError

**Comment by lra** [comment]
Can you dump a redacted json dump to see why you would have an unsupported ip protocol?

**Comment by EmpressDeIT** [comment]
ghoshtapo did you change your output to text from JSON?

https://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html

**Comment by jeffbildz** [comment]
Thanks for creating this awesome app!  I'm having the same issues as above and feel it's because other security groups are tied to the one being dumped and it's showing up as followed:
        "direction": "INGRESS",
        "from_port": null,
        "ip_protocol": "-1",
        "to_port": null

**Comment by lra** [comment]
I can't reproduce the issue, would you have more info to share?

**Comment by jeffbildz** [comment]
python main.py --region=xxxxx --profile=xxxx --vpc=vpc-xxxxx --csv
Traceback (most recent call last):
  File "main.py", line 379, in <module>
    main()
  File "main.py", line 375, in main
    print firewall.csv
  File "main.py", line 253, in csv
    for fr in self.rules:
  File "main.py", line 183, in rules
    rules_grants_cidr_ip=grant_row['cidr_ip'])
  File "main.py", line 63, in __init__
    assert rules_ip_protocol in (u'tcp', u'udp', u'icmp', "-1", None)
AssertionError

**Comment by jeffbildz** [comment]
Turning assertion off, I see the following output (truncated most and scrubbed):

None
{
   rules_grants_cidr_ip: 0.0.0.0/0
   name: TestRule1
   rules_ip_protocol: tcp
   rules_grants_name: None
   rules_from_port: 443
   rules_to_port: 443
   rules_direction: INGRESS
   id: sg-xxxxxx
   rules_grants_group_id: None
   description: Test Rule1
}
None
{
   rules_grants_cidr_ip: 0.0.0.0/0
   name: TestRule1
   rules_ip_protocol: tcp
   rules_grants_name: None
   rules_from_port: 8080
   rules_to_port: 8080
   rules_direction: INGRESS
   id: sg-xxxxx
   rules_grants_group_id: None
   description: Test Rule1
}
None
id,name,description,rules_direction,rules_ip_protocol,rules_from_port,rules_to_port,rules_grants_group_id,rules_grants_name,rules_grants_cidr_ip

**Comment by jeffbildz** [comment]
Fixed it with the following:

assert rules_ip_protocol in (u'tcp', u'udp', u'icmp', u'icmpv6', "-1", None)

Will need to edit additional protocols for v6.

**Comment by lra** [comment]
awesome, feel free to do a PR if you know how to

**Comment by lra** [comment]
Fixed in https://github.com/percolate/ec2-security-groups-dumper/issues/11

**Comment by powerupcloud** [comment]
Thanks for this great app. I am getting the below error for csv. Can you please help in fixing it?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ec2_security_groups_dumper/main.py", line 374, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/ec2_security_groups_dumper/main.py", line 370, in main
    print firewall.csv
  File "/usr/local/lib/python2.7/site-packages/ec2_security_groups_dumper/main.py", line 266, in csv
    for fr in self.rules:
  File "/usr/local/lib/python2.7/site-packages/ec2_security_groups_dumper/main.py", line 181, in rules
    rules_description=grant_row['description'])
  File "/usr/local/lib/python2.7/site-packages/ec2_security_groups_dumper/main.py", line 64, in __init__
    u'tcp', u'udp', u'icmp', u'icmpv6', "-1", None)
**AssertionError**

**Comment by powerupcloud** [comment]
I am able to fix by updating like below:

        assert rules_ip_protocol in (
            u'tcp', u'udp', u'icmp', u'icmpv6', "4", "50", "-1", None)

**Comment by jeffbildz** [comment]
Powerupcloud,

Can you submit a merge request so it gets reviewed and updated?

Thanks,

Jeff
